### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by ghost** [pureqh/bypassAV#3]
编译提示
`# command-line-arguments

./main.go:12:17: undefined: syscall.NewLazyDLL

./main.go:25:17: too many arguments in call to syscall.Syscall`

**Comment by pureqh** [comment]
需要使用windows 编译



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月26日(星期三) 下午4:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [pureqh/bypassAV] 编译错误 (#3)





 
编译提示
 `# command-line-arguments
 
./main.go:12:17: undefined: syscall.NewLazyDLL
 
./main.go:25:17: too many arguments in call to syscall.Syscall`

**Comment by ghost** [comment]
已经解决了。强。 @pureqh
