### ISSUE TITLE
编译需要Windows的api 所以要Windows环境编译&nbsp;&nbsp;

### ISSUE THREAD

**Issue by cinasea123** [pureqh/bypassAV#5]
大佬 win10自带的已经开始杀了 有cs的特征

**Comment by pureqh** [comment]
defender是吧


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月4日 22:14:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [pureqh/bypassAV] 编译需要Windows的api 所以要Windows环境编译   (#5)




 
大佬 win10自带的已经开始杀了 有cs的特征

**Comment by cinasea123** [comment]
对 检测到了CobaltStrike.G!nri和Wacatac.B!ml

**Comment by pureqh** [comment]
过段时间再搞搞吧 🌚🌚


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月4日 22:14:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [pureqh/bypassAV] 编译需要Windows的api 所以要Windows环境编译   (#5)




 
大佬 win10自带的已经开始杀了 有cs的特征

**Comment by cinasea123** [comment]
好吧 等大佬最新版

**Comment by ghost** [comment]
@pureqh 大佬。这个加载器的行为好像是被360检测到了。shell下运行直接拒绝访问，360提示检测到正在有黑客入侵服务器。没报病毒。
